### ISSUE TITLE
Picasa is not working

### ISSUE THREAD

**Issue by lvallera** [andrez47/thumbnail-zoom#1]
I am a fan of this addon put unfortunatley it stopped working in picasa.
I don't know if it's because of the https or other reason.
Could you please tell me how i can put it to work in picasa?

Thank you and good job

**Comment by andrez47** [comment]
Hi, thanks for your feedback. 
I fixed this issue and it'll be working on the next update. 

Regards,
Andres

**Comment by lvallera** [comment]
Hello,
Thank you for your quick response.
Can i ask you when will the new update be released?

Thx

**Comment by andrez47** [comment]
I think I'll upload a new version this week. But, it might be delayed on the Mozilla review process.

**Comment by lvallera** [comment]
Thank you.
I'll be checking for an update.
