### ISSUE TITLE
not working for German Sites of Amazon and Google

### ISSUE THREAD

**Issue by AndyK70** [andrez47/thumbnail-zoom#2]
Hi there,

very nice AddOn for the Fox, but could you enable it not only for google.com and amazon.com, but also for google.de and amazon.de ?
Would be very nice.

**Comment by andrez47** [comment]
That's right, I'll work on it! Thanks.

**Comment by andrez47** [comment]
That was fixed, so it will in the next release, hopefully this week. Thanks again!
