### ISSUE TITLE
Gmail won't load emails

### ISSUE THREAD

**Issue by JustinB4** [andrez47/thumbnail-zoom#20]
Gmail won't load emails when this plugin is enabled.  If I disable it then gmail works again.  I am using the new gmail layout.

**Comment by dadler** [comment]
You might try Thumbnail Zoom Plus https://addons.mozilla.org/en-US/firefox/addon/thumbnail-zoom-plus/ (the version of the add-on I maintain).  Gmail works for me in that version.

**Comment by JustinB4** [comment]
Thanks.  That worked.
