### ISSUE TITLE
not work on mozilla 4?

### ISSUE THREAD

**Issue by bayusetya** [andrez47/thumbnail-zoom#4]
in mozilla 4 just display a line... with about 1 or 2px width...

**Comment by andrez47** [comment]
Hi, currently It's working for me with the latest Fx version, I will appreciate if you can specify on which site and OS is that happening in order to fix it? 
Thanks for the feedback!

**Comment by bayusetya** [comment]
I'm use Windows 7 Ultimate with SP 1 updated.
I'm testing on facebook and amazon still have some problem.

PS: I'm upgrade firefox from 3.xx to 4 (no replace or remove first)

**Comment by andrez47** [comment]
Thanks I will investigate!

**Comment by bayusetya** [comment]
Sorry... :D
Now is working perfectly...
Maybe I need to restart Computer before all work perfectly...

PS: Thank's for the nice addons :D

**Comment by andrez47** [comment]
Ok thanks!
